<script lang="ts">
 import {onMount,tick} from 'svelte';
 import {Flower2,Smartphone,X,Images,UserRound,LogOut} from 'lucide-svelte';
 import {page} from '$app/state';
 import {inInstalledApp} from '$lib/pwa';
 let installed=$state(false),open=$state(false),installEvent=$state<any>(null),dialog=$state<HTMLDivElement>();let previous:HTMLElement|null=null;
 onMount(()=>{const media=matchMedia('(display-mode: standalone)');const sync=()=>installed=inInstalledApp();
 sync();const ready=(e:Event)=>{e.preventDefault();installEvent=e;},done=()=>{installed=true;open=false;installEvent=null;},requested=()=>{void install();};media.addEventListener('change',sync);window.addEventListener('beforeinstallprompt',ready);window.addEventListener('appinstalled',done);window.addEventListener('rose-install',requested);return()=>{media.removeEventListener('change',sync);window.removeEventListener('beforeinstallprompt',ready);window.removeEventListener('appinstalled',done);window.removeEventListener('rose-install',requested);};});
 async function install(){if(installEvent){await installEvent.prompt();installEvent=null;}else{previous=document.activeElement as HTMLElement;open=true;await tick();dialog?.querySelector<HTMLButtonElement>('button')?.focus();}}
 function close(){open=false;previous?.focus();}
 function keys(e:KeyboardEvent){if(e.key==='Escape')close();if(e.key==='Tab'&&dialog){const b=dialog.querySelectorAll<HTMLButtonElement>('button'),first=b[0],last=b[b.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
</script>
<header class="header"><a href="/" class="brand" aria-label="Rose Atelier home"><span class="brand-mark"><Flower2 size={23} strokeWidth={1.5}/></span><span>rose <i>atelier</i><small>THE NAIL STUDIO</small></span></a><div class="header-right"><a class="gallery-nav" href="/gallery"><Images size={18}/><span>My gallery</span></a>{#if page.data.user}<div class="account-menu"><span class="account-email" title={page.data.user.email}>{page.data.user.email}</span><form method="POST" action="/auth/logout"><button class="signout-btn" aria-label="Sign out" title="Sign out"><LogOut size={17}/></button></form></div>{:else if page.url.pathname!=='/login'}<a class="account-link" href="/login"><UserRound size={17}/><span>Sign in</span></a>{/if}{#if !installed}<button class="install-btn" onclick={install}><Smartphone size={16}/><span>Get the app</span></button>{/if}</div></header>
{#if open}<div class="modal-backdrop" role="presentation"><div class="install-modal" role="dialog" aria-modal="true" aria-labelledby="install-title" tabindex="-1" bind:this={dialog} onkeydown={keys}><button class="close-modal" onclick={close} aria-label="Close installation instructions"><X size={20}/></button><span class="modal-icon"><Flower2 size={30}/></span><h2 id="install-title">Your little pocket atelier</h2><p>Keep your nail studio a tap away.</p><div><b>On iPhone or iPad</b><p>Open in Safari, tap Share, then “Add to Home Screen.”</p><b>On Android</b><p>Open in Chrome, then choose “Install app” or “Add to Home screen” in the menu.</p></div><button class="primary" onclick={close}>Got it, lovely</button></div></div>{/if}
