<script lang="ts">import {translate,dateLocale} from '$lib/i18n';const t=(text:string)=>translate(page.data.lang,text);
 import LanguageSwitch from '$lib/LanguageSwitch.svelte';
 import {onMount,tick} from 'svelte';
 import {Flower2,Smartphone,X,Images,UserRound,LogOut} from 'lucide-svelte';
 import {page} from '$app/state';
 import {inInstalledApp} from '$lib/pwa';
 let installed=$state(false),open=$state(false),ready=$state(false),installing=$state(false),dialog=$state<HTMLDivElement>();let previous:HTMLElement|null=null;
 let device=$state<'ios'|'android'|'desktop'>('desktop'),embedded=$state(false),message=$state('');
 onMount(()=>{const ua=navigator.userAgent;device=/iPad|iPhone|iPod/.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)?'ios':/Android/.test(ua)?'android':'desktop';embedded=/Instagram|FBAN|FBAV|Snapchat|; wv\)/i.test(ua);
 const media=matchMedia('(display-mode: standalone)');const sync=()=>{installed=inInstalledApp()||!!window.roseInstall?.installed;ready=!!window.roseInstall?.prompt;if(installed){open=false;installing=false;}};
 sync();const requested=()=>{void install();};media.addEventListener('change',sync);window.addEventListener('rose-install-state',sync);window.addEventListener('rose-install',requested);return()=>{media.removeEventListener('change',sync);window.removeEventListener('rose-install-state',sync);window.removeEventListener('rose-install',requested);};});
 async function install(){if(installing||installed)return;message='';const event=window.roseInstall?.prompt;
 if(event){installing=true;try{const showing=event.prompt();window.roseInstall!.prompt=null;ready=false;await showing;const choice=await event.userChoice;if(choice.outcome==='accepted'){open=true;message='Installation requested. When it finishes, open Rose Atelier from your home screen.';}else{open=true;message='Installation was cancelled. You can try again from your browser menu.';}}catch{open=true;message='The browser could not open its install prompt. Use the browser menu below.';}finally{installing=false;}}else{previous=document.activeElement as HTMLElement;open=true;await tick();dialog?.querySelector<HTMLButtonElement>('button')?.focus();}}
 async function copyLink(){try{await navigator.clipboard.writeText(window.location.origin);message='Link copied. Paste it into '+(device==='ios'?'Safari.':'Chrome or Edge.');}catch{message='Open this address in '+(device==='ios'?'Safari: ':'Chrome or Edge: ')+window.location.origin;}}
 function close(){open=false;previous?.focus();}
 function keys(e:KeyboardEvent){if(e.key==='Escape')close();if(e.key==='Tab'&&dialog){const b=dialog.querySelectorAll<HTMLButtonElement>('button'),first=b[0],last=b[b.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
</script>
<header class="header"><a href="/" class="brand" aria-label={t("Rose Atelier home")}><span class="brand-mark"><Flower2 size={23} strokeWidth={1.5}/></span><span>rose <i>atelier</i><small>{t("THE NAIL STUDIO")}</small></span></a><div class="header-right"><LanguageSwitch/><a class="gallery-nav" href="/gallery"><Images size={18}/><span>{t("My gallery")}</span></a>{#if page.data.user}<div class="account-menu"><span class="account-email" title={page.data.user.email}>{page.data.user.email}</span><form method="POST" action="/auth/logout"><button class="signout-btn" aria-label={t("Sign out")} title={t("Sign out")}><LogOut size={17}/></button></form></div>{:else if page.url.pathname!=='/login'}<a class="account-link" href="/login"><UserRound size={17}/><span>{t("Sign in")}</span></a>{/if}{#if !installed}<button class="install-btn" aria-label={ready?t("Install app"):t("How to install")} onclick={install} disabled={installing}><Smartphone size={16}/><span>{installing?t("Installing…"):ready?t("Install app"):t("How to install")}</span></button>{/if}</div></header>
{#if open}<div class="modal-backdrop" role="presentation"><div class="install-modal" role="dialog" aria-modal="true" aria-labelledby="install-title" tabindex="-1" bind:this={dialog} onkeydown={keys}><button class="close-modal" onclick={close} aria-label={t("Close installation instructions")}><X size={20}/></button><span class="modal-icon"><Flower2 size={30}/></span><h2 id="install-title">{t("Your little pocket atelier")}</h2>
{#if ready}<p>{t("Your browser is ready. Tap below to open its installation prompt.")}</p><button class="primary" onclick={install} disabled={installing}><Smartphone size={17}/>{t("Install Rose Atelier")}</button>
{:else if embedded}<p>{t("First, open Rose Atelier in")} {device==='ios'?'Safari':t("Chrome")}{t(". Installation isn’t available inside this app’s browser.")}</p><div><b>{t("Open in your browser")}</b><p>{t("Use this app’s menu and choose “Open in browser,” or copy the link and paste it into")} {device==='ios'?'Safari':t("Chrome")}.</p></div><button class="primary" onclick={copyLink}>{t("Copy app link")}</button>
{:else if device==='ios'}<p>{t("On iPhone and iPad, installation happens in Safari’s Share menu.")}</p><div><b>{t("01 · Open this page in Safari")}</b><p>{t("Tap the Share icon in the browser toolbar.")}</p><b>{t("02 · Add to Home Screen")}</b><p>{t("Choose “Add to Home Screen,” keep “Open as Web App” enabled if shown, then tap “Add.”")}</p><b>{t("03 · Open your atelier")}</b><p>{t("Tap the Rose Atelier icon on your home screen to start creating.")}</p></div>
{:else if device==='android'}<p>{t("The browser hasn’t offered its automatic install prompt yet. You can use Chrome’s menu now.")}</p><div><b>{t("01 · Open in Chrome")}</b><p>{t("Use the regular browser, outside Instagram or Snapchat.")}</p><b>{t("02 · Use the ⋮ menu")}</b><p>{t("Choose “Add to Home screen,” then “Install” if offered, and confirm.")}</p><b>{t("03 · Open the app icon")}</b><p>{t("Return to your home screen and open Rose Atelier.")}</p></div>
{:else}<p>{t("Use Chrome or Edge to install Rose Atelier on your computer.")}</p><div><b>{t("Install from the browser")}</b><p>{t("Look for the install icon in the address bar, or choose “Install Rose Atelier” / “Install this site as an app” from the browser menu.")}</p><b>{t("Already installed?")}</b><p>{t("Open Rose Atelier from your applications or Start menu.")}</p></div>{/if}
{#if message}<p role="status">{t(message)}</p>{/if}<button class="secondary" onclick={close}>{t("Got it, lovely")}</button></div></div>{/if}