<script lang="ts">
 import {Sparkles,Share2,Copy,Download,LoaderCircle,Check} from 'lucide-svelte';
 import {storyFiles,downloadStories} from '$lib/story';
 let {poll}:{poll:{id:string;title:string;options:{position:number;image:string;shape:string}[]}}=$props();
 let files=$state<File[]>([]),preparing=$state(false),message=$state(''),copied=$state(false);
 const link=$derived(typeof window!=='undefined'?`${window.location.origin}/p/${poll.id}`:'');
 async function copy(){try{await navigator.clipboard.writeText(link);copied=true;message='Poll link copied. Add it as a link sticker in your story.';}catch{message='Copy the poll link shown below.';}}
 async function prepare(){if(preparing)return;preparing=true;message='';try{files=await storyFiles(poll.title,poll.options);message='Your four story images are ready.';}catch(e){message=e instanceof Error?e.message:'Stories could not be prepared. Try again.';}finally{preparing=false;}}
 async function share(){if(!files.length)return;try{if(navigator.canShare?.({files})){await navigator.share({files});message='Add the poll URL as a link sticker before posting your story.';}else{downloadStories(files);message='Images downloaded. Add them to your story, then add the poll URL as a link sticker.';}}catch(e){if((e as Error).name!=='AbortError')message='Sharing did not open. Try downloading the four images instead.';}}
</script>
<section class="share-poll-card"><span class="eyebrow"><Sparkles size={13}/> YOUR STORY, THEIR FAVORITE</span><h2>Let your friends pick.</h2><p>Share these four looks to Instagram or Snapchat, then add your poll link as a story link sticker.</p><div class="copy-link"><input aria-label="Public poll link" value={link} readonly onclick={e=>e.currentTarget.select()}/><button onclick={copy}>{#if copied}<Check size={16}/>{:else}<Copy size={16}/>{/if}Copy link</button></div><div class="share-actions">{#if !files.length}<button class="primary" onclick={prepare} disabled={preparing}>{#if preparing}<LoaderCircle size={17} class="spin"/>Preparing…{:else}<Sparkles size={17}/>Prepare 4 story images{/if}</button>{:else}<button class="primary" onclick={share}><Share2 size={17}/>Share story images</button><button class="secondary" onclick={()=>downloadStories(files)}><Download size={17}/>Download all 4</button><div class="story-file-links">{#each files as file,i}<button onclick={()=>downloadStories([file])}>Save look {i+1}</button>{/each}</div>{/if}</div><p class="share-message" role="status">{message}</p><small>Your phone chooses which apps appear in the share menu. If Instagram or Snapchat doesn’t appear, save the images and import them there.</small></section>
