<script lang="ts">import {translate,dateLocale} from '$lib/i18n';import {page} from '$app/state';const t=(text:string)=>translate(page.data.lang,text);
 import {onMount,tick} from 'svelte';
 import {Sparkles,Share2,Copy,Download,LoaderCircle,Check,Instagram} from 'lucide-svelte';
 import {storyFiles,downloadStories} from '$lib/story';
 let {poll}:{poll:{id:string;title:string;options:{position:number;image:string;shape:string}[]}}=$props();
 let files=$state<File[]>([]),preparing=$state(false),message=$state(''),copied=$state(false);
 $effect(()=>{page.data.lang;files=[];});
 const link=$derived(typeof window!=='undefined'?`${window.location.origin}/p/${poll.id}`:'');
 const pinterestUrl=$derived(typeof window!=='undefined'?`https://www.pinterest.com/pin/create/button/?url=${encodeURIComponent(link)}&media=${encodeURIComponent(new URL(poll.options[0].image,window.location.origin).href)}&description=${encodeURIComponent(`${poll.title} · ${t('Vote for your favorite manicure:')}`)}`:'');
 async function copy(){try{await navigator.clipboard.writeText(link);copied=true;message='Poll link copied. Paste it into your story or share it with your friends.';}catch{message='Copy the poll link shown below.';}}
 async function prepare(){if(preparing||files.length)return;preparing=true;message='';try{const language=page.data.lang;const prepared=await storyFiles(poll.title,poll.options,language);if(language===page.data.lang){files=prepared;await tick();void loadSnapchat();}}catch(e){message=e instanceof Error?e.message:'Stories could not be prepared. Try again.';}finally{preparing=false;}}
 async function share(){if(!files.length)return;const shareData={files,title:poll.title,text:t('Vote for your favorite manicure:'),url:link};try{if(navigator.share&&navigator.canShare?.({files,url:link})){await navigator.share(shareData);message='Your story images and poll link were shared.';}else if(navigator.share){await navigator.share({title:poll.title,text:`${t('Vote for your favorite manicure:')} ${link}`,url:link});downloadStories(files);message='Poll link shared. Your story images were downloaded so you can add one to your story.';}else{await copy();downloadStories(files);message='Poll link copied and story images downloaded. Add both to your story.';}}catch(e){if((e as Error).name!=='AbortError'){downloadStories(files);message='Poll link sharing did not open. Your story images were downloaded; copy the poll link below.';}}}
 async function shareInstagram(){if(!files.length)return;const image=files[0];try{if(navigator.share&&navigator.canShare?.({files:[image]})){await navigator.share({files:[image],title:poll.title,text:`${t('Vote for your favorite manicure:')} ${link}`,url:link});message='Instagram share sheet opened. Choose Instagram to continue.';}else if(navigator.share){await navigator.share({title:poll.title,text:`${t('Vote for your favorite manicure:')} ${link}`,url:link});downloadStories([image]);message='Poll link shared. Story image downloaded; open Instagram and add it to your story.';}else{downloadStories([image]);await copy();message='Story image downloaded and poll link copied. Open Instagram to add them to your story.';}}catch(e){if((e as Error).name!=='AbortError')message='Instagram sharing did not open. Download the story image and copy the poll link below.';}}
 async function loadSnapchat(){let script=document.getElementById('snapkit-creative-kit-sdk') as HTMLScriptElement|null;if(!script){script=document.createElement('script');script.id='snapkit-creative-kit-sdk';script.src='https://sdk.snapkit.com/js/v1/create.js';script.async=true;document.head.append(script);}try{await new Promise<void>((resolve,reject)=>{if((window as Window&{snap?:unknown}).snap){resolve();return;}script!.addEventListener('load',()=>resolve(),{once:true});script!.addEventListener('error',()=>reject(new Error('Snapchat sharing could not load.')),{once:true});});const snapWindow=window as Window&{snap?:{creativekit?:{initalizeShareButtons:(buttons:HTMLCollection)=>void}}};snapWindow.snap?.creativekit?.initalizeShareButtons(document.getElementsByClassName('snapchat-share-button'));}catch{message='Snapchat sharing could not load. Copy the poll link to share it there.';}}
 onMount(()=>{void prepare();});
</script>
<section class="share-poll-card"><span class="eyebrow"><Sparkles size={13}/> {t("YOUR STORY, THEIR FAVORITE")}</span><h2>{t("Let your friends pick.")}</h2><p>{t("Share your poll story and link together, or copy the link to send it separately.")}</p><div class="copy-link"><input aria-label={t("Public poll link")} value={link} readonly onclick={e=>e.currentTarget.select()}/><button onclick={copy}>{#if copied}<Check size={16}/>{:else}<Copy size={16}/>{/if}{t("Copy link")}</button></div><div class="share-actions">{#if !files.length}<button class="primary" onclick={prepare} disabled={preparing}>{#if preparing}<LoaderCircle size={17} class="spin"/>{t("Preparing your story…")}{:else}<Sparkles size={17}/>{t("Prepare story images")}{/if}</button>{:else}<button class="primary" onclick={share}><Share2 size={17}/>{t("Share your poll")}</button><div class="platform-share-actions"><button class="secondary" onclick={shareInstagram}><Instagram size={17}/>{t("Instagram Stories")}</button><button class="secondary snapchat-share-button" data-share-url={link}><span class="platform-mark">S</span>{t("Snapchat Story")}</button><a class="secondary" href={pinterestUrl} target="_blank" rel="noreferrer"><span class="platform-mark">P</span>{t("Pinterest Pin")}</a></div><button class="secondary" onclick={()=>downloadStories(files)}><Download size={17}/>{t("Download story images")}</button><div class="story-file-links">{#each files as file,i}<button onclick={()=>downloadStories([file])}>{t("Save look")} {i+1}</button>{/each}</div>{/if}</div><p class="share-message" role="status">{t(message)}</p><small>{t("If your social app doesn’t accept both together, share the poll link in your story text or paste it into a link sticker.")}</small></section>
