import {translate,type Language} from './i18n';
export type StoryOption={position:number;image:string;shape:string};
function cover(ctx:CanvasRenderingContext2D,img:HTMLImageElement,x:number,y:number,w:number,h:number){const scale=Math.max(w/img.width,h/img.height),iw=img.width*scale,ih=img.height*scale;ctx.save();ctx.beginPath();ctx.roundRect(x,y,w,h,38);ctx.clip();ctx.drawImage(img,x+(w-iw)/2,y+(h-ih)/2,iw,ih);ctx.restore();}
export async function storyFiles(title:string,options:StoryOption[],language:Language='en'){
 const t=(text:string)=>translate(language,text);
 const photos=await Promise.all(options.map(async o=>{const r=await fetch(o.image);if(!r.ok)throw new Error('A look could not load. Please try again.');const url=URL.createObjectURL(await r.blob()),img=new Image();img.src=url;try{await img.decode();return {img,url};}catch(e){URL.revokeObjectURL(url);throw e;}}));
 try{return await Promise.all(options.map(async(o,i)=>{const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1920;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Your browser could not prepare these stories.');const gradient=ctx.createLinearGradient(0,0,1080,1920);gradient.addColorStop(0,'#fff8fb');gradient.addColorStop(1,'#efd2df');ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1920);ctx.fillStyle='#a92354';ctx.textAlign='center';ctx.font='32px sans-serif';ctx.fillText(t('HELP ME PICK MY NEXT MANICURE'),540,170);ctx.fillStyle='#572d42';ctx.font='italic 64px Georgia';ctx.fillText(title.length>30?t('Which look is your favorite?'):title,540,275,960);cover(ctx,photos[i].img,70,365,940,1160);ctx.fillStyle='#a92354';ctx.beginPath();ctx.arc(540,1530,62,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 50px sans-serif';ctx.fillText(String(i+1),540,1548);ctx.fillStyle='#6e3e57';ctx.font='32px sans-serif';ctx.fillText(t('Tap my link to vote ♡'),540,1690);ctx.font='italic 44px Georgia';ctx.fillText('rose atelier',540,1820);ctx.font='22px sans-serif';ctx.fillText(language==='fr'?`LOOK ${i+1} SUR 4 · MES ENVIES DE MANUCURE`:`LOOK ${i+1} OF 4 · MY AI NAIL LOOKBOOK`,540,1865);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not export this story.')),'image/jpeg',.92));return new File([blob],`rose-atelier-look-${i+1}.jpg`,{type:'image/jpeg'});}));}finally{photos.forEach(p=>URL.revokeObjectURL(p.url));}
}
export function downloadStories(files:File[]){for(const file of files){const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}}
