<script lang="ts">import {translate,dateLocale} from '$lib/i18n';import {page} from '$app/state';const t=(text:string)=>translate(page.data.lang,text);
 import AppHeader from '$lib/AppHeader.svelte';import {onMount} from 'svelte';import {Sparkles,Images,Download,RefreshCw,ArrowLeft,Vote,Check,X,LoaderCircle} from 'lucide-svelte';
 type Design={id:string;prompt:string;shape:string;created:number};let designs=$state<Design[]>([]),loading=$state(true),message=$state(''),selecting=$state(false),selected=$state<string[]>([]),title=$state('Help me pick my next manicure'),publishing=$state(false),pollError=$state('');let creationKey='';
 const designCount=$derived(designs.length);
 function personalizedPollTitle(){const name=page.data.user?.name?.trim().split(/\s+/)[0];return name?t('Help {name} pick her next manicure').replace('{name}',name):t('Help me pick my next manicure');}
 function toggle(id:string){if(publishing)return;if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length<4)selected=[...selected,id];}
 function begin(){if(title==='Help me pick my next manicure'||title==='Quelle manucure tu me conseilles ?'||title.startsWith('Help ')||title.startsWith('Aide '))title=personalizedPollTitle();selecting=true;selected=[];pollError='';creationKey=crypto.randomUUID();}
 async function publish(){if(selected.length<2||selected.length>4||publishing)return;publishing=true;pollError='';try{const r=await fetch('/api/polls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({designs:selected,title,key:creationKey})}),d=await r.json();if(!r.ok)throw new Error(d.message||'Your poll could not be created.');window.location.assign(`/p/${d.id}`);}catch(e){pollError=e instanceof Error?e.message:'Your poll could not be created.';publishing=false;}}
 async function load(){loading=true;message='';try{const r=await fetch('/api/gallery',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.message||'Your gallery could not load.');designs=d.designs;}catch(e){message=e instanceof Error?e.message:'Your gallery could not load.';}finally{loading=false;}}
 onMount(load);
</script>
<svelte:head><title>{t("My Gallery — Rose Atelier")}</title></svelte:head>
<div class="app-shell"><AppHeader/><main class="gallery-main" id="ask-friends"><a class="back-link" href="/"><ArrowLeft size={16}/> {t("Back to your atelier")}</a><div class="gallery-heading"><div><span class="eyebrow">{t("YOUR PERSONAL LOOKBOOK")}</span><h1>{t("A collection of")} <i>{t("you.")}</i></h1><p>{t("Your designs, saved for every little obsession. Pick any 2–4 designs from your gallery to let your friends choose their favorite.")}</p></div><a class="primary" href="/studio"><Sparkles size={17}/> {t("Create a new look")}</a></div>
 {#if !loading&&!message}<div class="gallery-poll-toolbar"><div><span class="eyebrow">{t("YOUR SAVED LOOKS")}</span><p>{page.data.lang==='fr'?`${designCount} look${designCount===1?'':'s'} dans ta galerie · 2 pour un sondage`:`${designCount} saved ${designCount===1?'look':'looks'} · pick any 2 for a poll`}</p></div><button class="primary poll-invite-button" onclick={begin} disabled={designCount<2||selecting}><Vote size={18}/>{t("Let your friends decide for you")}</button><a href="/polls">{t("My polls →")}</a></div>{/if}
 {#if selecting}<section class="poll-composer"><button class="composer-close" aria-label={t("Cancel poll selection")} onclick={()=>selecting=false} disabled={publishing}><X size={18}/></button><span class="eyebrow">{t("LET YOUR FRIENDS PICK")}</span><h2>{t("Let your friends pick their favorite.")}</h2><p>{t("Choose any 2–4 designs in your gallery. Your selection order sets their numbers.")}</p><label for="poll-title">{t("Your poll question")}</label><input id="poll-title" bind:value={title} maxlength="90" disabled={publishing}/><div class="selected-four">{#each Array(4) as _,i}<span>{#if selected[i]}<img src={`/api/gallery/${selected[i]}/image`} alt={`${t("Selected look")} ${i+1}`}/><b>{i+1}</b>{:else}<b>{i+1}</b>{/if}</span>{/each}</div><p class="public-photo-note">{t("Publishing makes these images and your display name visible on your public poll page. Your other designs and prompts stay private.")}</p>{#if pollError}<p class="error-message" role="alert">{t(pollError)}</p>{/if}<button class="primary" onclick={publish} disabled={selected.length<2||selected.length>4||publishing||!title.trim()}>{#if publishing}<LoaderCircle size={17} class="spin"/>{t("Publishing…")}{:else}<Vote size={17}/>{t("Publish my poll ·")} {selected.length}/4{/if}</button></section>{/if}
 {#if loading}<div class="gallery-empty" role="status">{t("Opening your little lookbook…")}</div>{:else if message}<div class="gallery-empty" role="alert"><p>{t(message)}</p><button class="primary" onclick={load}><RefreshCw size={16}/> {t("Try again")}</button></div>{:else if !designs.length}<div class="gallery-empty"><span class="empty-flower"><Images size={36}/></span><h2>{t("Your next favorite look starts here.")}</h2><p>{t("Create your first manicure and we’ll keep it in your little lookbook.")}</p><a class="primary" href="/studio"><Sparkles size={17}/> {t("Generate a nail design")}</a></div>{:else}<div class="gallery-grid">{#each designs as design}<article class="gallery-card" class:poll-selected={selected.includes(design.id)}>{#if selecting}<button class="choose-poll-image" onclick={()=>toggle(design.id)} disabled={publishing||(!selected.includes(design.id)&&selected.length===4)} aria-pressed={selected.includes(design.id)} aria-label={page.data.lang==='fr'?`Choisir ${t(design.shape)} pour le sondage`:`Select ${design.shape} for your poll`}><img src={`/api/gallery/${design.id}/image`} alt={design.prompt} loading="lazy"/><span class="gallery-choice-number">{#if selected.includes(design.id)}{selected.indexOf(design.id)+1}{:else}<Check size={16}/>{/if}</span></button>{:else}<a href={`/api/gallery/${design.id}/image`} target="_blank" rel="noreferrer"><img src={`/api/gallery/${design.id}/image`} alt={design.prompt} loading="lazy"/></a>{/if}<div><span class="eyebrow">{t(design.shape)}</span><h2>{new Date(design.created).toLocaleDateString(dateLocale(page.data.lang),{month:'short',day:'numeric',year:'numeric'})}</h2><details><summary>{t("View design prompt")}</summary><p>{design.prompt}</p></details><a class="save-btn" href={`/api/gallery/${design.id}/image`} download="rose-atelier-manicure.jpg"><Download size={16}/> {t("Save look")}</a></div></article>{/each}</div>{/if}</main></div>
