// Server integration checks: real Supabase Auth, compiled SvelteKit routes,
// SQLite-backed D1 interface, and an in-memory R2 interface. No emails are sent.
// Run after building: node scripts/verify-auth.mjs
import assert from 'node:assert/strict';
import {readFileSync,readdirSync,mkdirSync} from 'node:fs';
import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import {createClient} from '@supabase/supabase-js';
import {Server} from '../.svelte-kit/output/server/index.js';
import {manifest} from '../.svelte-kit/cloudflare-tmp/manifest.js';

function readEnv(path){const values={};for(const line of readFileSync(path,'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Z_]+)\s*=\s*(.*)$/);if(m)values[m[1]]=m[2].trim().replace(/^(['"])(.*)\1$/,'$2');}return values;}
const supplied=readEnv('../.env.local'),local=readEnv('.env.local');
const url=local.SUPABASE_URL,key=local.SUPABASE_ANON_KEY,adminKey=supplied.SUPABASE_SERVICE_ROLE_KEY;
assert(url&&key&&adminKey,'Supabase test credentials are required in the ignored environment files');
const admin=createClient(url,adminKey,{auth:{persistSession:false,autoRefreshToken:false},global:{fetch:(input,init)=>fetch(input,{...init,signal:AbortSignal.timeout(15000)})}});
const sqlite=new DatabaseSync(':memory:');
for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync(`drizzle/${file}`,'utf8').replaceAll('--> statement-breakpoint',''));
const DB={prepare(sql){const statement=sqlite.prepare(sql);let parameters=[];return {bind(...values){parameters=values;return this;},async run(){return statement.run(...parameters);},async first(){return statement.get(...parameters)||null;},async all(){return {results:statement.all(...parameters)};}};}};
DB.batch=async statements=>{sqlite.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}};
mkdirSync('.sites-runtime',{recursive:true});
await build({stdin:{contents:"export * from './src/lib/server/access.ts';",resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',packages:'external',outfile:'.sites-runtime/access-check.mjs'});
const access=await import('../.sites-runtime/access-check.mjs');
const objects=new Map();
const BUCKET={async put(name,bytes,options){objects.set(name,{bytes,httpMetadata:options.httpMetadata});},async get(name){const object=objects.get(name);return object?{body:new Blob([object.bytes]).stream(),httpMetadata:object.httpMetadata}:null;}};
const server=new Server(manifest),origin='https://auth-check.invalid',env={...local,DB,BUCKET,FAL_API_KEY:'integration-test-signing-key'};
await server.init({env});
const created=[];
class Browser {
 constructor(){this.cookies=new Map();}
 async request(path,{method='GET',form,json,headers={}}={}){
  const target=new URL(path,origin);const sent=[...this.cookies].filter(([,cookie])=>target.pathname.startsWith(cookie.path)).map(([name,c])=>`${name}=${c.value}`).join('; ');
  const request=new Request(target,{method,headers:{cookie:sent,accept:target.pathname.startsWith('/api/')?'application/json':'text/html',...(method==='POST'?{'content-type':json?'application/json':'application/x-www-form-urlencoded',origin}:{}),...headers},body:json?JSON.stringify(json):form?new URLSearchParams(form):undefined});
  const response=await server.respond(request,{platform:{env,ctx:{waitUntil(){}}},getClientAddress:()=> '127.0.0.1'});
  for(const line of response.headers.getSetCookie()){
   const pair=line.split(';')[0],index=pair.indexOf('='),name=pair.slice(0,index),value=pair.slice(index+1),path=line.match(/;\s*Path=([^;]+)/i)?.[1]||'/';
   if(/;\s*Max-Age=0(?:;|$)/i.test(line)||value==='')this.cookies.delete(name);else this.cookies.set(name,{value,path});
  }
  return response;
 }
}
async function account(){const email=`rose-auth-check-${crypto.randomUUID()}@example.com`,password=`Rose!${crypto.randomUUID()}aA1`;const {data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true});if(error)throw new Error(`Could not create temporary account: ${error.code||error.status}`);created.push(data.user.id);return {email,password,id:data.user.id};}
async function step(name,fn){await fn();console.log(`PASS ${name}`);}
let failed=false;
try{
 const a=await account(),b=await account(),first=new Browser(),second=new Browser(),guest=new Browser();
 await step('studio shows install gate; private pages redirect to sign-in',async()=>{const studio=await guest.request('/studio');assert.equal(studio.status,200);assert.match(await studio.text(),/home screen/);for(const route of ['/gallery','/auth/password','/polls']){const r=await guest.request(route);assert.equal(r.status,303);assert(r.headers.get('location').startsWith('/login?next='));}});
 await step('browser generation and inspiration are gated; gallery requires authentication',async()=>{for(const route of ['/api/preview','/api/inspire','/api/app-session'])assert.equal((await guest.request(route,{method:'POST',json:{}})).status,403);for(const route of ['/api/gallery','/api/gallery/example/image'])assert.equal((await guest.request(route)).status,401);});
 await step('signup rejects a weak password without sending an email',async()=>{const r=await guest.request('/login?/signup',{method:'POST',form:{email:a.email,password:'short'}});assert.equal(r.status,400);const body=await r.text();assert.match(body,/8–128 characters/);assert.match(body,/A little space/);});
 await step('email/password login sets secure HttpOnly session cookies and rejects external redirects',async()=>{const r=await first.request('/login?/signin',{method:'POST',form:{email:a.email,password:a.password,next:'https://example.com/untrusted'}});assert.equal(r.status,303);assert.equal(r.headers.get('location'),'/studio');const sessionCookies=r.headers.getSetCookie().filter(c=>/^rose-auth(?:\.|=)/.test(c));assert(sessionCookies.length);for(const cookie of sessionCookies){assert.match(cookie,/HttpOnly/i);assert.match(cookie,/Secure/i);assert.match(cookie,/SameSite=Lax/i);}});
 await step('authenticated studio renders install gate and gallery loads',async()=>{const r=await first.request('/studio');assert.equal(r.status,200);assert.match(await r.text(),/home screen/);const gallery=await first.request('/api/gallery');assert.equal(gallery.status,200);assert.deepEqual((await gallery.json()).designs,[]);});
 await step('second account signs in independently',async()=>{const r=await second.request('/login?/signin',{method:'POST',form:{email:b.email,password:b.password,next:'/gallery'}});assert.equal(r.status,303);assert.equal(r.headers.get('location'),'/gallery');});
 const imageId=crypto.randomUUID(),objectKey='integration/first-user';
 sqlite.prepare('INSERT INTO designs (id,owner,prompt,shape,created,object_key) VALUES (?,?,?,?,?,?)').run(imageId,a.id,'Private account A manicure','Short & round',Date.now(),objectKey);
 objects.set(objectKey,{bytes:new Uint8Array([1,2,3]),httpMetadata:{contentType:'image/jpeg'}});
 await step('gallery list and images isolate accounts',async()=>{const listA=await (await first.request('/api/gallery')).json(),listB=await (await second.request('/api/gallery')).json();assert.equal(listA.designs.length,1);assert.equal(listB.designs.length,0);assert.equal((await first.request(`/api/gallery/${imageId}/image`)).status,200);assert.equal((await second.request(`/api/gallery/${imageId}/image`)).status,404);});
 await step('tampered session cookie cannot authenticate',async()=>{const tampered=new Browser();tampered.cookies.set('rose-auth',{value:encodeURIComponent('base64-not-a-session'),path:'/'});const r=await tampered.request('/api/gallery');assert.equal(r.status,401);});
 await step('guest gallery transfers once to the signed-in account',async()=>{const browser=new Browser(),token=Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))),n=>n.toString(16).padStart(2,'0')).join('');const id=crypto.randomUUID();sqlite.prepare('INSERT INTO designs (id,owner,prompt,shape,created) VALUES (?,?,?,?,?)').run(id,hash,'Guest design','Long almond',Date.now());browser.cookies.set('rose-gallery',{value:token,path:'/'});const r=await browser.request('/login?/signin',{method:'POST',form:{email:a.email,password:a.password}});assert.equal(r.status,303);assert.equal(sqlite.prepare('SELECT owner FROM designs WHERE id = ?').get(id).owner,a.id);assert(!browser.cookies.has('rose-gallery'));});
 await step('preview cookies are bound to the verified account',async()=>{const requestId=crypto.randomUUID(),timestamp=String(Date.now());const keyBytes=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.FAL_API_KEY),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signature=Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',keyBytes,new TextEncoder().encode(`${requestId}.${timestamp}.${a.id}`))),n=>n.toString(16).padStart(2,'0')).join('');second.cookies.set('rose-job',{value:`${requestId}.${timestamp}.${signature}`,path:'/api/preview'});assert.equal((await second.request('/api/preview')).status,403);});
 await step('password mismatch is rejected without changing the account',async()=>{const r=await first.request('/auth/password',{method:'POST',form:{password:'A new secure password!1',confirmation:'different'}});assert.equal(r.status,400);assert.match(await r.text(),/don’t match/);});
 await step('invalid confirmation links recover to sign-in',async()=>{const r=await guest.request('/auth/confirm?type=invalid&token_hash=invalid');assert.equal(r.status,303);assert.equal(r.headers.get('location'),'/login?notice=expired');});
 await step('token-hash password recovery and password update work without email delivery',async()=>{const {data,error}=await admin.auth.admin.generateLink({type:'recovery',email:a.email});if(error)throw new Error(`Recovery link generation failed: ${error.code}`);const recovering=new Browser();const r=await recovering.request(`/auth/confirm?type=recovery&token_hash=${encodeURIComponent(data.properties.hashed_token)}`);assert.equal(r.status,303);assert.equal(r.headers.get('location'),'/auth/password');const password=`New!${crypto.randomUUID()}1aA`;const updated=await recovering.request('/auth/password',{method:'POST',form:{password,confirmation:password}});assert.equal(updated.status,303);a.password=password;const check=new Browser();assert.equal((await check.request('/login?/signin',{method:'POST',form:{email:a.email,password}})).status,303);});
 await step('cross-origin logout is rejected',async()=>{const r=await second.request('/auth/logout',{method:'POST',headers:{origin:'https://example.com'}});assert.equal(r.status,403);});
 await step('logout removes session and preview cookies and blocks private APIs',async()=>{const r=await second.request('/auth/logout',{method:'POST'});assert.equal(r.status,303);assert.equal((await second.request('/api/gallery')).status,401);assert(![...second.cookies.keys()].some(n=>n==='rose-auth'||n.startsWith('rose-auth.')));assert(!second.cookies.has('rose-job'));});
 await step('guest allowance, private preview and registered download gate',async()=>{const r=await guest.request('/api/app-session',{method:'POST',json:{},headers:{'x-rose-app':'standalone'}});assert.equal(r.status,200);assert.equal((await r.json()).remaining,1);const token=decodeURIComponent(guest.cookies.get('rose-gallery').value),owner=await access.hash(token),id=crypto.randomUUID();sqlite.prepare('INSERT INTO designs (id,owner,prompt,shape,created,object_key) VALUES (?,?,?,?,?,?)').run(id,owner,'Guest preview','Short & round',Date.now(),objectKey);assert.equal((await guest.request(`/api/preview/image?id=${id}`)).status,200);assert.equal((await guest.request(`/api/preview/image?id=${id}&download=1`)).status,401);assert.equal((await (await guest.request('/api/allowance')).json()).remaining,0);assert.equal((await new Browser().request(`/api/preview/image?id=${id}`)).status,401);});
 assert.equal((await first.request('/login?/signin',{method:'POST',form:{email:a.email,password:a.password}})).status,303);
 assert.equal((await second.request('/login?/signin',{method:'POST',form:{email:b.email,password:b.password}})).status,303);
 const makeEvent=(id,metadata={},guestToken)=>({locals:{user:id?{id,app_metadata:metadata}:null},cookies:{get:name=>name==='rose-gallery'?guestToken:undefined},platform:{env},request:new Request(origin,{headers:{'x-rose-app':'standalone'}}),getClientAddress:()=>crypto.randomUUID()});
 await step('atomic quotas: guest one, free five, premium twenty; expiry and user metadata cannot upgrade',async()=>{for(const [limit,id,meta,token] of [[1,null,{},'a'.repeat(64)],[5,crypto.randomUUID(),{},null],[20,crypto.randomUUID(),{rose_plan:'premium',rose_premium_until:new Date(Date.now()+86400000).toISOString()},null]]){const event=makeEvent(id,meta,token);for(let i=0;i<limit;i++){const reservation=await access.reserveGeneration(event);sqlite.prepare("UPDATE generation_attempts SET status='completed' WHERE id=?").run(reservation.id);}assert.equal((await access.allowance(event)).remaining,0);await assert.rejects(()=>access.reserveGeneration(event),e=>e.status===(id?429:401));}assert.equal(access.plan(makeEvent('expired',{rose_plan:'premium',rose_premium_until:'2000-01-01'})),'free');const spoof=makeEvent('spoof');spoof.locals.user.user_metadata={rose_plan:'premium',rose_premium_until:'2099-01-01'};assert.equal(access.plan(spoof),'free');const event=makeEvent(crypto.randomUUID());const raced=await Promise.allSettled(Array.from({length:8},()=>access.reserveGeneration(event)));assert.equal(raced.filter(r=>r.status==='fulfilled').length,1);const reservation=raced.find(r=>r.status==='fulfilled').value;sqlite.prepare("UPDATE generation_attempts SET status='failed' WHERE id=?").run(reservation.id);assert.equal((await access.allowance(event)).used,0);assert.equal(access.dayWindow(Date.parse('2026-10-03T23:59:59Z')).day,'2026-10-03');});
 await step('persistent inspiration cooldown and global generation capacity',async()=>{const event=makeEvent(crypto.randomUUID());await access.reserveInspiration(event);await assert.rejects(()=>access.reserveInspiration(event),e=>e.status===429);env.DAILY_STUDIO_LIMIT=1;await assert.rejects(()=>access.reserveGeneration(makeEvent(crypto.randomUUID())),e=>e.status===429);delete env.DAILY_STUDIO_LIMIT;});
 await step('public four-look poll, idempotent creation and voting, private image isolation, owner closure',async()=>{const ids=[];for(let i=0;i<4;i++){const id=crypto.randomUUID();ids.push(id);sqlite.prepare('INSERT INTO designs (id,owner,prompt,shape,created,object_key) VALUES (?,?,?,?,?,?)').run(id,a.id,'Hidden private prompt','Short & round',Date.now(),objectKey);}const key=crypto.randomUUID(),body={designs:ids,title:'Choose my next manicure',key};const r=await first.request('/api/polls',{method:'POST',json:body});assert.equal(r.status,201);const {id}=await r.json();const retry=await first.request('/api/polls',{method:'POST',json:body});assert.equal((await retry.json()).id,id);assert.equal((await second.request('/api/polls',{method:'POST',json:{...body,key:crypto.randomUUID()}})).status,400);const voter=new Browser();const view=await voter.request(`/api/polls/${id}`);assert.equal(view.status,200);const publicPoll=await view.json();assert.equal(publicPoll.options.length,4);assert(!JSON.stringify(publicPoll).includes('Hidden private prompt'));assert.equal((await voter.request(`/api/polls/${id}/image/0`)).status,200);assert.equal((await voter.request(`/api/gallery/${ids[0]}/image`)).status,401);for(const position of [0,1])assert.equal((await voter.request(`/api/polls/${id}/vote`,{method:'POST',json:{position}})).status,200);const result=await (await voter.request(`/api/polls/${id}`)).json();assert.equal(result.total,1);assert.equal(result.myVote,0);assert.equal((await second.request(`/api/polls/${id}/close`,{method:'POST',json:{}})).status,404);assert.equal((await first.request(`/api/polls/${id}/close`,{method:'POST',json:{}})).status,200);assert.equal((await new Browser().request(`/api/polls/${id}/vote`,{method:'POST',json:{position:2}})).status,409);assert.equal((await voter.request(`/p/${id}`)).status,200);});
 console.log('Server authentication, quotas and poll integration checks passed. No paid generation calls. Google consent and mobile UI are not exercised.');
}catch(e){failed=true;console.error(`FAIL ${e.message}`);}finally{for(const id of created){const {error}=await admin.auth.admin.deleteUser(id);if(error){failed=true;console.error(`Temporary account cleanup failed for ${id}: ${error.code||error.status}`);}}sqlite.close();console.log(`Temporary account cleanup completed (${created.length} accounts).`);}
if(failed)process.exitCode=1;
