<script lang="ts">
 import {onMount,untrack} from 'svelte';import AppHeader from '$lib/AppHeader.svelte';import SharePoll from '$lib/SharePoll.svelte';import {Heart,Check,Vote,LockKeyhole,Sparkles,LoaderCircle} from 'lucide-svelte';import type {PageProps} from './$types';
 let {data}:PageProps=$props();let poll=$state(untrack(()=>data.poll)),selected=$state<number|null>(null),sending=$state(false),closing=$state(false),message=$state('');
 const showResults=$derived(poll.myVote!==null||poll.isOwner||!!poll.closed);
 async function refresh(){const response=await fetch(`/api/polls/${poll.id}`,{cache:'no-store'});if(response.ok){poll=await response.json();return true;}return false;}
 async function vote(){if(selected===null||sending||poll.closed||poll.myVote!==null)return;sending=true;message='';try{const r=await fetch(`/api/polls/${poll.id}/vote`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({position:selected})}),d=await r.json();if(!r.ok){await refresh();throw new Error(d.message||'Your vote could not be saved.');}poll=d;message='Your vote is in. A little help, a lovely new look.';}catch(e){message=e instanceof Error?e.message:'Your vote could not be saved. Please try again.';}finally{sending=false;}}
 async function close(){if(closing)return;closing=true;message='';try{const r=await fetch(`/api/polls/${poll.id}/close`,{method:'POST'}),d=await r.json();if(!r.ok)throw new Error(d.message);await refresh();message='Your poll is closed. These are the final results.';}catch(e){message=e instanceof Error?e.message:'Your poll could not be closed.';}finally{closing=false;}}
 onMount(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;async function update(){if(stopped)return;if(!document.hidden&&!poll.closed)try{await refresh();}catch{message='Live results are reconnecting…';}if(!stopped&&!poll.closed)timer=setTimeout(update,2500);}timer=setTimeout(update,2500);return()=>{stopped=true;clearTimeout(timer);};});
</script>
<svelte:head><title>{poll.title} — Vote on Rose Atelier</title><meta name="description" content="Four nail designs. One favorite. Vote for the manicure you love, then create a look of your own."/><meta property="og:title" content={poll.title}/><meta property="og:description" content="Help me pick my next manicure. Vote for your favorite of four AI nail designs."/><meta property="og:image" content={`${new URL(data.url).origin}${poll.options[0].image}`}/><meta property="og:url" content={data.url}/><meta property="og:type" content="website"/><meta name="robots" content="noindex,follow"/></svelte:head>
<div class="app-shell"><AppHeader/><main class="poll-main"><div class="poll-intro"><span class="eyebrow"><Heart size={13}/> A LITTLE HELP FROM YOU</span><h1>{poll.title}</h1><p>{poll.closed?'The votes are in. Here’s the final favorite.':poll.isOwner?'Your friends are choosing. Results update every few seconds.':poll.myVote!==null?'Thanks for voting. Watch the favorites take shape.':'Four looks, one favorite. Which manicure would you choose?'}</p><span class="poll-status" class:closed={!!poll.closed}>{#if poll.closed}<LockKeyhole size={13}/>Poll closed{:else}<span class="live-dot"></span>Voting is open{/if}{#if showResults}<b>{poll.total} {poll.total===1?'vote':'votes'}</b>{/if}</span></div><div class="vote-grid">{#each poll.options as option}<button class="vote-look" class:selected={selected===option.position||poll.myVote===option.position} disabled={!!poll.closed||poll.myVote!==null||sending||poll.isOwner} aria-pressed={selected===option.position||poll.myVote===option.position} onclick={()=>selected=option.position}><div class="vote-photo"><img src={option.image} alt={`Nail design ${option.position+1}: ${option.shape}`}/><span class="look-number">{option.position+1}</span>{#if poll.myVote===option.position}<span class="voted-tag"><Check size={13}/>Your vote</span>{/if}</div><div class="vote-caption"><span>Look {option.position+1}</span>{#if showResults}<b>{poll.total?Math.round(option.votes/poll.total*100):0}%</b>{:else}<span class="vote-circle">{#if selected===option.position}<Check size={15}/>{/if}</span>{/if}</div>{#if showResults}<div class="vote-track"><span style={`width:${poll.total?option.votes/poll.total*100:0}%`}></span></div><small>{option.votes} {option.votes===1?'vote':'votes'}</small>{/if}</button>{/each}</div>{#if !poll.closed&&poll.myVote===null&&!poll.isOwner}<button class="primary cast-vote" disabled={selected===null||sending} onclick={vote}>{#if sending}<LoaderCircle size={18} class="spin"/>Saving your vote…{:else}<Vote size={19}/>Vote for look {selected===null?'…':selected+1}{/if}</button><p class="vote-note">No account needed. One vote per browser.</p>{/if}{#if message}<p class="poll-message" role="status">{message}</p>{/if}
 {#if poll.isOwner}<div class="poll-owner-actions">{#if !poll.closed}<button class="secondary" onclick={close} disabled={closing}><LockKeyhole size={15}/>{closing?'Closing…':'Close poll and keep final results'}</button>{/if}<a href="/polls">My polls</a></div><SharePoll {poll}/>{:else if poll.myVote!==null||poll.closed}<section class="voter-convert"><span class="eyebrow">YOUR TURN TO DREAM</span><h2>Now imagine these<br/><i>on your own nails.</i></h2><p>Install your little nail atelier and try one design for free. No account needed for your first preview.</p><a class="primary" href="/studio"><Sparkles size={18}/>Create my own nail design</a><small>Want more? A free account includes 5 designs a day.</small></section>{/if}</main></div>
