<script lang="ts">import {translate,dateLocale} from '$lib/i18n';import {page} from '$app/state';const t=(text:string)=>translate(page.data.lang,text);
 import {enhance} from '$app/forms';
 import {untrack} from 'svelte';
 import AppHeader from '$lib/AppHeader.svelte';
 import {Sparkles,Heart,Mail,LockKeyhole,ArrowRight,Eye,EyeOff,LoaderCircle,CheckCircle2} from 'lucide-svelte';
 import type {PageProps} from './$types';
 let {data,form}:PageProps=$props();
 let mode=$state<'signin'|'signup'|'reset'>(untrack(()=>form?.mode==='signup'||form?.mode==='reset'?form.mode:data.initialMode==='signup'?'signup':'signin')),showPassword=$state(false),pending=$state(false);
 let email=$state(untrack(()=>form?.email||''));
 $effect(()=>{if(form?.mode==='signup'||form?.mode==='reset'||form?.mode==='signin')mode=form.mode;});
 function switchMode(next:typeof mode){mode=next;showPassword=false;}
 const heading=$derived(mode==='signup'?'A little space, just for you.':mode==='reset'?'Let’s get you back in.':'Welcome to your little atelier.');
</script>
<svelte:head><title>{mode==='signup'?t("Create your account"):mode==='reset'?t("Reset your password"):t("Sign in")} — Rose Atelier</title><meta name="robots" content="noindex"/></svelte:head>
<div class="app-shell"><AppHeader/><main class="auth-main"><div class="auth-scene"><img src="/manicure.jpg" alt={t("Soft pink nails, ready for your next look")}/><div class="auth-scene-copy"><span class="eyebrow">{t("YOUR LITTLE NAIL UNIVERSE")}</span><h1>{t("A little polish.")}<br/><i>{t("A lot of you.")}</i></h1><p>{t("Your ideas, your favorite looks,")}<br/>{t("your very own nail atelier.")}</p><span><Heart size={15}/> {t("A little self-expression, saved.")}</span></div></div><section class="auth-card"><span class="auth-flower"><Sparkles size={25} strokeWidth={1.4}/></span><span class="eyebrow">{mode==='reset'?t("A FRESH START"):t("YOUR PERSONAL NAIL ATELIER")}</span><h1>{t(heading)}</h1><p class="auth-intro">{mode==='signup'?t("Create an account to imagine your next manicure and keep every look you love."):mode==='reset'?t("Enter your email and we’ll send you a link to choose a new password."):t("Sign in to create something lovely and revisit your favorite designs.")}</p>
 {#if mode!=='reset'}<div class="auth-tabs"><button type="button" class:active={mode==='signin'} aria-pressed={mode==='signin'} onclick={()=>switchMode('signin')} disabled={pending}>{t("Sign in")}</button><button type="button" class:active={mode==='signup'} aria-pressed={mode==='signup'} onclick={()=>switchMode('signup')} disabled={pending}>{t("Create account")}</button></div>
 <form method="POST" action="?/google"><input type="hidden" name="next" value={data.next}/><button class="google-button" disabled={!data.configured||!data.googleEnabled||pending}><svg viewBox="0 0 24 24" width="19" height="19" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2.1H12v4h5.4a4.6 4.6 0 0 1-2 3v2.5h3.2c1.9-1.8 3-4.4 3-7.4Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.6-2.4l-3.2-2.5c-.9.6-2 .9-3.4.9-2.6 0-4.8-1.8-5.6-4.2H3.1v2.6A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.4 13.8a6 6 0 0 1 0-3.6V7.6H3.1a10 10 0 0 0 0 8.8l3.3-2.6Z"/><path fill="#EA4335" d="M12 6c1.5 0 2.8.5 3.8 1.5l2.9-2.9A9.6 9.6 0 0 0 12 2a10 10 0 0 0-8.9 5.6l3.3 2.6C7.2 7.8 9.4 6 12 6Z"/></svg>{t("Continue with Google")}</button></form>{#if data.configured&&!data.googleEnabled}<p class="auth-provider-note">{t("Google sign-in is coming soon. Email is ready below.")}</p>{/if}<div class="auth-divider"><span>{t("or with your email")}</span></div>{/if}
 {#if !data.configured}<div class="auth-message error" role="alert">{t("The studio’s account connection is being set up. Please try again shortly.")}</div>{/if}
 {#if form?.message&&form.mode===mode}<div class="auth-message error" role="alert">{t(form.message)}</div>{/if}
 {#if form?.success&&form.mode===mode}<div class="auth-message success" role="status"><CheckCircle2 size={19}/><span>{t(form.success)}</span></div>{/if}
 {#if data.notice&&!form}<div class="auth-message" role="status">{t(data.notice)}</div>{/if}
 <form class="email-form" method="POST" action={`?/`+mode} use:enhance={()=>{pending=true;return async({update})=>{try{await update({reset:false});}finally{pending=false;}};}}>
  <input type="hidden" name="next" value={data.next}/>
  <label for="email">{t("Your email")}</label><div class="auth-input"><Mail size={17}/><input id="email" name="email" type="email" autocomplete="email" inputmode="email" placeholder="you@example.com" bind:value={email} required maxlength="254" disabled={pending}/></div>
  {#if mode!=='reset'}<div class="auth-password-label"><label for="password">{t("Your password")}</label>{#if mode==='signin'}<button type="button" onclick={()=>switchMode('reset')} disabled={pending}>{t("Forgot password?")}</button>{/if}</div><div class="auth-input"><LockKeyhole size={17}/><input id="password" name="password" type={showPassword?'text':'password'} autocomplete={mode==='signup'?'new-password':'current-password'} placeholder={mode==='signup'?t("At least 8 characters"):t("Your password")} minlength={mode==='signup'?8:1} maxlength="128" required disabled={pending}/><button type="button" class="password-eye" aria-label={showPassword?t("Hide password"):t("Show password")} onclick={()=>showPassword=!showPassword}>{#if showPassword}<EyeOff size={17}/>{:else}<Eye size={17}/>{/if}</button></div>{#if mode==='signup'}<p class="auth-password-hint">{t("At least 8 characters. A few unexpected words make a lovely strong password.")}</p>{/if}{/if}
  <button class="primary auth-submit" disabled={pending||!data.configured}>{#if pending}<LoaderCircle size={18} class="spin"/>{t("One little moment…")}{:else}{mode==='signup'?t("Create my account"):mode==='reset'?t("Send reset link"):t("Sign in to my atelier")}<ArrowRight size={17}/>{/if}</button>
 </form>
 {#if mode==='reset'}<button class="auth-back" onclick={()=>switchMode('signin')} disabled={pending}>{t("Back to sign in")}</button>{/if}
 <p class="auth-bottom"><Heart size={12}/> {t("Your creations, kept just for you.")}</p><a class="auth-home" href="/">{t("Back to your atelier")}</a>
 </section></main></div>
